- name: Install zsh shell
  apt:
    name: zsh
    state: latest
    update_cache: yes
  become: true

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended

- name: Change shell to zsh
  shell: chsh -s /bin/zsh
  become: false


