- name: Install pyenv
  shell: >
    curl https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/"
  become: false

- name: Update .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: present
    create: no
    line: "{{ item }}"
  with_items:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'

